version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: testUser
      MONGO_INITDB_ROOT_PASSWORD: testPsw

  mongo-express:
    image: mongo-express
    restart: always
    ports:
       - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: testUser
      ME_CONFIG_MONGODB_ADMINPASSWORD: testPsw
      ME_CONFIG_MONGODB_URL: mongodb://testUser:testPsw@mongo:27017/

